# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5c253cc3b8ac8fa3de6ef62478ea838ed7a5c525127381469e1728295b0bc767c7fdcdf50766cbd8bf36f4def07c2cfd9af95ebd35a29fd137533d6c18095330

test:
  secret_key_base: bbc5e8fc4a21644ae8d995eda9071807cc5d2eee9ef50b2fdda6162480dac04554ea8f46278bd1b835900d35f526812865f1ac38e5fc51e2d651015b93bf9618

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
